"""Command-line interface for the agent factory system."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, List, Sequence

from .factory_agent import AgentFactory
from .integrations.microsoft_graph import GraphAuthConfig, MicrosoftGraphClient
from .integrations.outlook_local import OutlookLocalClient
from .outlook_workflow import suggest_reply_body, triage_messages
from .schemas import AgentBlueprint


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="agent-factory",
        description="Create and run machine-learning specialist agents.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    create_parser = subparsers.add_parser(
        "create-agent",
        help="Train and create a new specialist agent from a dataset and topic docs.",
    )
    create_parser.add_argument("--name", required=True, help="Agent name.")
    create_parser.add_argument("--description", required=True, help="Agent purpose.")
    create_parser.add_argument("--topic", required=True, help="Knowledge topic.")
    create_parser.add_argument(
        "--task-type",
        required=True,
        choices=["classification", "regression"],
        help="Task model type.",
    )
    create_parser.add_argument("--dataset", required=True, help="CSV training dataset path.")
    create_parser.add_argument(
        "--knowledge",
        required=True,
        nargs="+",
        help="One or more knowledge file/folder paths.",
    )
    create_parser.add_argument("--input-column", default="input", help="Input column name.")
    create_parser.add_argument("--target-column", default="target", help="Target column name.")
    create_parser.add_argument(
        "--output-dir",
        default="generated_agents",
        help="Folder where generated agents are stored.",
    )

    predict_parser = subparsers.add_parser("predict", help="Run a specialist agent task prediction.")
    predict_parser.add_argument("--agent-dir", required=True, help="Generated agent directory path.")
    predict_parser.add_argument("--input", required=True, help="Task input text.")

    ask_parser = subparsers.add_parser("ask", help="Ask a specialist agent a topic question.")
    ask_parser.add_argument("--agent-dir", required=True, help="Generated agent directory path.")
    ask_parser.add_argument("--question", required=True, help="Question text.")
    ask_parser.add_argument("--top-k", type=int, default=3, help="How many knowledge excerpts to return.")

    describe_parser = subparsers.add_parser("describe", help="Show metadata for a generated agent.")
    describe_parser.add_argument("--agent-dir", required=True, help="Generated agent directory path.")

    list_parser = subparsers.add_parser("list", help="List registered generated agents.")
    list_parser.add_argument(
        "--output-dir",
        default="generated_agents",
        help="Folder where generated agents are stored.",
    )

    outlook_inbox_parser = subparsers.add_parser(
        "outlook-inbox",
        help="Read inbox messages from Outlook via Microsoft Graph.",
    )
    outlook_inbox_parser.add_argument("--top", type=int, default=10, help="Number of messages to return (1-100).")
    outlook_inbox_parser.add_argument("--unread-only", action="store_true", help="Only return unread messages.")

    outlook_draft_parser = subparsers.add_parser(
        "outlook-draft-reply",
        help="Create a draft reply for an Outlook message.",
    )
    outlook_draft_parser.add_argument("--message-id", required=True, help="Outlook message id.")
    outlook_draft_parser.add_argument(
        "--body",
        help="Draft body text. If omitted, provide --agent-dir so body is generated by OutlookEmailManager.",
    )
    outlook_draft_parser.add_argument(
        "--agent-dir",
        help="Generated agent directory for OutlookEmailManager (used when --body is omitted).",
    )

    outlook_event_parser = subparsers.add_parser(
        "outlook-create-event",
        help="Create an Outlook calendar event via Microsoft Graph.",
    )
    outlook_event_parser.add_argument("--subject", required=True, help="Event subject.")
    outlook_event_parser.add_argument(
        "--start",
        required=True,
        help="Event start local datetime, format YYYY-MM-DDTHH:MM:SS.",
    )
    outlook_event_parser.add_argument(
        "--end",
        required=True,
        help="Event end local datetime, format YYYY-MM-DDTHH:MM:SS.",
    )
    outlook_event_parser.add_argument(
        "--timezone",
        default="Pacific Standard Time",
        help='Windows timezone id, for example "Pacific Standard Time".',
    )
    outlook_event_parser.add_argument(
        "--attendees",
        nargs="*",
        default=[],
        help="One or more attendee emails, supports comma-separated entries.",
    )
    outlook_event_parser.add_argument("--body", default="", help="Event body text.")

    outlook_triage_parser = subparsers.add_parser(
        "outlook-triage",
        help="Read inbox messages and classify them with OutlookEmailManager.",
    )
    outlook_triage_parser.add_argument("--agent-dir", required=True, help="OutlookEmailManager generated agent path.")
    outlook_triage_parser.add_argument("--top", type=int, default=10, help="Number of messages to triage.")
    outlook_triage_parser.add_argument("--unread-only", action="store_true", help="Only triage unread messages.")
    outlook_triage_parser.add_argument(
        "--auto-draft",
        action="store_true",
        help="Create draft replies for triaged messages predicted as draft_reply.",
    )
    outlook_triage_parser.add_argument(
        "--max-drafts",
        type=int,
        default=3,
        help="Maximum number of auto-created draft replies when --auto-draft is set.",
    )

    local_inbox_parser = subparsers.add_parser(
        "outlook-local-inbox",
        help="Read inbox messages from local Outlook Desktop (no Graph app registration required).",
    )
    local_inbox_parser.add_argument("--top", type=int, default=10, help="Number of messages to return (1-100).")
    local_inbox_parser.add_argument("--unread-only", action="store_true", help="Only return unread messages.")

    local_draft_parser = subparsers.add_parser(
        "outlook-local-draft-reply",
        help="Create a local Outlook draft reply using message EntryID.",
    )
    local_draft_parser.add_argument("--message-id", required=True, help="Outlook local message EntryID.")
    local_draft_parser.add_argument(
        "--body",
        help="Draft body text. If omitted, provide --agent-dir to auto-generate using OutlookEmailManager.",
    )
    local_draft_parser.add_argument(
        "--agent-dir",
        help="Generated agent directory for OutlookEmailManager (used when --body is omitted).",
    )

    local_event_parser = subparsers.add_parser(
        "outlook-local-create-event",
        help="Create an Outlook calendar event in local Outlook Desktop.",
    )
    local_event_parser.add_argument("--subject", required=True, help="Event subject.")
    local_event_parser.add_argument(
        "--start",
        required=True,
        help="Event start local datetime, format YYYY-MM-DDTHH:MM:SS.",
    )
    local_event_parser.add_argument(
        "--end",
        required=True,
        help="Event end local datetime, format YYYY-MM-DDTHH:MM:SS.",
    )
    local_event_parser.add_argument(
        "--attendees",
        nargs="*",
        default=[],
        help="One or more attendee emails, supports comma-separated entries.",
    )
    local_event_parser.add_argument("--body", default="", help="Event body text.")

    local_triage_parser = subparsers.add_parser(
        "outlook-local-triage",
        help="Read local Outlook inbox and classify messages with OutlookEmailManager.",
    )
    local_triage_parser.add_argument("--agent-dir", required=True, help="OutlookEmailManager generated agent path.")
    local_triage_parser.add_argument("--top", type=int, default=10, help="Number of messages to triage.")
    local_triage_parser.add_argument("--unread-only", action="store_true", help="Only triage unread messages.")
    local_triage_parser.add_argument(
        "--auto-draft",
        action="store_true",
        help="Create local draft replies for triaged messages predicted as draft_reply.",
    )
    local_triage_parser.add_argument(
        "--max-drafts",
        type=int,
        default=3,
        help="Maximum number of auto-created draft replies when --auto-draft is set.",
    )

    return parser


def _handle_create(args: argparse.Namespace) -> None:
    blueprint = AgentBlueprint(
        name=args.name,
        description=args.description,
        topic=args.topic,
        task_type=args.task_type,
        input_column=args.input_column,
        target_column=args.target_column,
    )
    factory = AgentFactory(output_root=args.output_dir)
    agent_dir = factory.create_specialist_agent(
        blueprint=blueprint,
        dataset_path=Path(args.dataset),
        knowledge_paths=[Path(path) for path in args.knowledge],
    )
    specialist = factory.load_specialist_agent(agent_dir)
    print(
        json.dumps(
            {
                "created_agent_dir": str(agent_dir.resolve()),
                "blueprint": specialist.describe()["blueprint"],
                "training": specialist.describe()["training"],
            },
            indent=2,
        )
    )


def _handle_predict(args: argparse.Namespace) -> None:
    specialist = AgentFactory().load_specialist_agent(Path(args.agent_dir))
    result = specialist.predict(args.input)
    print(json.dumps(result, indent=2))


def _handle_ask(args: argparse.Namespace) -> None:
    specialist = AgentFactory().load_specialist_agent(Path(args.agent_dir))
    result = specialist.ask_topic_question(args.question, top_k=args.top_k)
    print(json.dumps(result, indent=2))


def _handle_describe(args: argparse.Namespace) -> None:
    specialist = AgentFactory().load_specialist_agent(Path(args.agent_dir))
    print(json.dumps(specialist.describe(), indent=2))


def _handle_list(args: argparse.Namespace) -> None:
    factory = AgentFactory(output_root=args.output_dir)
    print(json.dumps(factory.list_registered_agents(), indent=2))


def _build_graph_client() -> MicrosoftGraphClient:
    config = GraphAuthConfig.from_env()
    return MicrosoftGraphClient(config)


def _build_local_outlook_client() -> OutlookLocalClient:
    return OutlookLocalClient()


def _extract_sender(message: dict) -> dict:
    sender = message.get("from", {}).get("emailAddress", {})
    return {
        "name": sender.get("name"),
        "email": sender.get("address"),
    }


def _handle_outlook_inbox(args: argparse.Namespace) -> None:
    client = _build_graph_client()
    messages = client.get_inbox_messages(top=args.top, unread_only=args.unread_only)

    payload = []
    for message in messages:
        payload.append(
            {
                "id": message.get("id"),
                "subject": message.get("subject"),
                "from": _extract_sender(message),
                "receivedDateTime": message.get("receivedDateTime"),
                "isRead": message.get("isRead"),
                "bodyPreview": message.get("bodyPreview"),
                "webLink": message.get("webLink"),
            }
        )
    print(json.dumps(payload, indent=2))


def _handle_outlook_draft_reply(args: argparse.Namespace) -> None:
    client = _build_graph_client()
    body = (args.body or "").strip()
    generated_from_prediction = None

    if not body:
        if not args.agent_dir:
            raise ValueError("Either --body or --agent-dir is required for outlook-draft-reply.")
        specialist = AgentFactory().load_specialist_agent(Path(args.agent_dir))
        message = client.get_message(args.message_id)
        generated_from_prediction, body = suggest_reply_body(specialist, message)

    draft = client.create_reply_draft(args.message_id, body)
    output = {
        "draft": draft,
        "body_preview": body,
    }
    if generated_from_prediction:
        output["generated_from_prediction"] = generated_from_prediction

    print(json.dumps(output, indent=2))


def _split_attendees(raw_values: List[str]) -> List[str]:
    attendees: List[str] = []
    for raw in raw_values:
        items = [item.strip() for item in raw.split(",")]
        attendees.extend(item for item in items if item)
    return attendees


def _handle_outlook_create_event(args: argparse.Namespace) -> None:
    client = _build_graph_client()
    attendees = _split_attendees(args.attendees)
    event = client.create_calendar_event(
        subject=args.subject,
        start_datetime=args.start,
        end_datetime=args.end,
        timezone=args.timezone,
        attendees=attendees,
        body_text=args.body,
    )
    print(json.dumps(event, indent=2))


def _handle_outlook_triage(args: argparse.Namespace) -> None:
    specialist = AgentFactory().load_specialist_agent(Path(args.agent_dir))
    client = _build_graph_client()
    messages = client.get_inbox_messages(top=args.top, unread_only=args.unread_only)
    triaged = triage_messages(specialist, messages)

    drafts: List[dict[str, Any]] = []
    if args.auto_draft:
        max_drafts = max(0, args.max_drafts)
        for message, triage_result in zip(messages, triaged):
            if len(drafts) >= max_drafts:
                break
            if triage_result.get("prediction") != "draft_reply":
                continue

            generated_from_prediction, body = suggest_reply_body(specialist, message)
            draft = client.create_reply_draft(message["id"], body)
            drafts.append(
                {
                    "source_message_id": message.get("id"),
                    "generated_from_prediction": generated_from_prediction,
                    "draft_id": draft.get("draft_id"),
                    "web_link": draft.get("web_link"),
                }
            )

    print(
        json.dumps(
            {
                "triaged_messages": triaged,
                "drafts_created": drafts,
            },
            indent=2,
        )
    )


def _handle_outlook_local_inbox(args: argparse.Namespace) -> None:
    client = _build_local_outlook_client()
    messages = client.get_inbox_messages(top=args.top, unread_only=args.unread_only)

    payload = []
    for message in messages:
        payload.append(
            {
                "id": message.get("id"),
                "subject": message.get("subject"),
                "from": _extract_sender(message),
                "receivedDateTime": message.get("receivedDateTime"),
                "isRead": message.get("isRead"),
                "bodyPreview": message.get("bodyPreview"),
            }
        )
    print(json.dumps(payload, indent=2))


def _handle_outlook_local_draft_reply(args: argparse.Namespace) -> None:
    client = _build_local_outlook_client()
    body = (args.body or "").strip()
    generated_from_prediction = None

    if not body:
        if not args.agent_dir:
            raise ValueError("Either --body or --agent-dir is required for outlook-local-draft-reply.")
        specialist = AgentFactory().load_specialist_agent(Path(args.agent_dir))
        message = client.get_message(args.message_id)
        generated_from_prediction, body = suggest_reply_body(specialist, message)

    draft = client.create_reply_draft(args.message_id, body)
    output = {
        "draft": draft,
        "body_preview": body,
    }
    if generated_from_prediction:
        output["generated_from_prediction"] = generated_from_prediction
    print(json.dumps(output, indent=2))


def _handle_outlook_local_create_event(args: argparse.Namespace) -> None:
    client = _build_local_outlook_client()
    attendees = _split_attendees(args.attendees)
    event = client.create_calendar_event(
        subject=args.subject,
        start_datetime=args.start,
        end_datetime=args.end,
        attendees=attendees,
        body_text=args.body,
    )
    print(json.dumps(event, indent=2))


def _handle_outlook_local_triage(args: argparse.Namespace) -> None:
    specialist = AgentFactory().load_specialist_agent(Path(args.agent_dir))
    client = _build_local_outlook_client()
    messages = client.get_inbox_messages(top=args.top, unread_only=args.unread_only)
    triaged = triage_messages(specialist, messages)

    drafts: List[dict[str, Any]] = []
    if args.auto_draft:
        max_drafts = max(0, args.max_drafts)
        for message, triage_result in zip(messages, triaged):
            if len(drafts) >= max_drafts:
                break
            if triage_result.get("prediction") != "draft_reply":
                continue

            generated_from_prediction, body = suggest_reply_body(specialist, message)
            draft = client.create_reply_draft(message["id"], body)
            drafts.append(
                {
                    "source_message_id": message.get("id"),
                    "generated_from_prediction": generated_from_prediction,
                    "draft_id": draft.get("draft_id"),
                }
            )

    print(
        json.dumps(
            {
                "triaged_messages": triaged,
                "drafts_created": drafts,
            },
            indent=2,
        )
    )


def main(argv: Sequence[str] | None = None) -> None:
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "create-agent":
            _handle_create(args)
        elif args.command == "predict":
            _handle_predict(args)
        elif args.command == "ask":
            _handle_ask(args)
        elif args.command == "describe":
            _handle_describe(args)
        elif args.command == "list":
            _handle_list(args)
        elif args.command == "outlook-inbox":
            _handle_outlook_inbox(args)
        elif args.command == "outlook-draft-reply":
            _handle_outlook_draft_reply(args)
        elif args.command == "outlook-create-event":
            _handle_outlook_create_event(args)
        elif args.command == "outlook-triage":
            _handle_outlook_triage(args)
        elif args.command == "outlook-local-inbox":
            _handle_outlook_local_inbox(args)
        elif args.command == "outlook-local-draft-reply":
            _handle_outlook_local_draft_reply(args)
        elif args.command == "outlook-local-create-event":
            _handle_outlook_local_create_event(args)
        elif args.command == "outlook-local-triage":
            _handle_outlook_local_triage(args)
        else:
            parser.error(f"Unknown command: {args.command}")
    except (ValueError, RuntimeError) as error:
        print(f"Error: {error}", file=sys.stderr)
        raise SystemExit(1) from error


if __name__ == "__main__":
    main()
